spring.application.name=banking-backend
spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/onlinebanking
spring.datasource.username=root
spring.datasource.password=YOUR_DB_PASSWORD_HERE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key=YOUR_RAZORPAY_KEY_HERE
razorpay.secret=YOUR_RAZORPAY_SECRET_HERE
